/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.caihua.usb;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.util.Queue;
import java.io.PrintStream;
import java.net.InetAddress;

import com.caihua.ui.online.ReaderActivity;

public class UdpThread extends Thread {
	static DatagramPacket packet;
	Queue<byte[]> recequen;
	static DatagramSocket udpSocket;

	public void run() {
		// :( Parsing error. Please contact me.
	}

	class dobs extends Thread {

		public void run() {
			// :( Parsing error. Please contact me.
		}
	}

	static int count = 0x0;

	public static synchronized void send(byte[] bs, int star, int length) {
		if (packet == null) {
			try {
				System.out.println(ReaderActivity.jmip);
				System.out.println(ReaderActivity.jmport);
				packet = new DatagramPacket(bs, length,
						InetAddress.getByName(ReaderActivity.jmip),
						Integer.parseInt(ReaderActivity.jmport));
			} catch (Exception localException1) {
			}
		}
		try {
			if (packet != null) {
				packet.setData(bs, star, length);
				udpSocket.send(packet);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
