/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package com.caihua.camera;

import android.os.Handler;
import android.graphics.Rect;
import android.os.Message;

public class RecognitionThread extends Thread implements Runnable {
    private String imgPath;
    private String imgPathHead;
    private boolean isPhoto;
    private Handler mHandler;
    private OcrManager ocrManager;
    private Rect rect;
    private byte[] data = null;
    private boolean isBlurOn = true;
    
    public RecognitionThread(Handler handler, byte[] data, OcrManager ocrManager, Rect rect, boolean isPhoto, boolean isBlurOn, String imgPath, String imgPathHead) {
        mHandler = handler;
        data = data;
        ocrManager = ocrManager;
        rect = rect;
        isPhoto = isPhoto;
        isBlurOn = isBlurOn;
        imgPathHead = imgPathHead;
    }
    
    public void run() {
        Message msg = mHandler.obtainMessage();
        IdCardInfo idCardInfo = ocrManager.recognitionPhoto(data, 0x2, rect, mHandler, isPhoto, isBlurOn, imgPath, imgPathHead);
        if(isPhoto) {
            if(idCardInfo == null) {
                mHandler.sendEmptyMessageDelayed(0x9, 0x64);
                return;
            }
            msg.what = 0x2;
            msg.obj = idCardInfo;
            mHandler.sendMessage(msg);
            return;
        }
        if(idCardInfo == null) {
            msg.what = 0x3;
            mHandler.sendMessage(msg);
            return;
        }
        if(idCardInfo.getResultType() != 0x6) {
            msg.what = 0x2;
            msg.obj = idCardInfo;
            mHandler.sendMessage(msg);
        }
    }
}
