/**
 * Generated by smali2java 1.0.0.558
 * Copyright (C) 2013 Hensence.com
 */

package com.caihua.camera;

import java.io.UnsupportedEncodingException;
import android.util.Log;

public class StringManager {

	public StringManager() {
	}

	public void finalize() {
	}

	public static String convertGbkToUnicode(byte[] array) {
		String str = null;
		try {
			byte[] text = filterAndCut(array);
			if (text != null) {
				str = new String(text, "GBK");
			} else {

			}
		} catch (UnsupportedEncodingException e) {
			Log.e("convert", e.toString());
		}
		return str.trim();
	}

	public static byte[] filterAndCut(byte[] array) {
        int len = strlen(array);
        if(len < 0x1) {
        	//????
           // int localconst/41 = 0x0;
        	return null;
        }
        byte[] filter = new byte[len];
        for(int i = 0x0, cnt = 0x0; i < len; i = i + 0x1) {
            if(array[i] == 0xd) {
                continue;
            }
            filter[(cnt ++)] = array[i];
        }
        return filter;
    }

	public static int strlen(byte[] array) {
		int len = -0x1;
		if (array != null) {
			if (array.length == 0) {
				return len;
			}
			for (int i = 0x0; i < array.length; i = i + 0x1) {
				if (array[i] == 0) {
					return i;
				}
			}
		}
		return len;
	}

	public static byte[] convertUnicodeToAscii(String str) {
		byte[] b = null;
		try {
			if (str != null) {
				b = str.getBytes("US-ASCII");
			} else {
			}
		} catch (UnsupportedEncodingException e) {
			Log.e("convert", e.toString());
		}
		return b;
	}
}
